import type { Metadata } from "next";
import { Inter, Alegreya, Aleo } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const alegreya = Alegreya({ subsets: ["latin"] });
const aleo = Aleo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={aleo.className}>{children}</body>
    </html>
  );
}
